### ISSUE TITLE
LNURLw error

### ISSUE THREAD

**Issue by frennkie** [arcbtc/lnbits#18]
I'm runnning LNBits with the LNURLw extention on `localhost` for testing. When I try to create a withdrawal link I have received 500 INTERNAL SERVER ERROR and the journal contains  a `lnurl.exceptions.InvalidUrl`.

.env: 

```
...
LNBITS_FORCE_HTTPS=0
...
```

Apr 25 09:59:50 host sh[32242]: Traceback (most recent call last):
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/lnurl/core.py", line 24, in encode
Apr 25 09:59:50 host sh[32242]:     return Lnurl(_url_encode(url))
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/lnurl/types.py", line 164, in __init__
Apr 25 09:59:50 host sh[32242]:     self.url = url if url else self.__get_url__(bech32)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/lnurl/types.py", line 168, in __get_url__
Apr 25 09:59:50 host sh[32242]:     return parse_obj_as(Union[TorUrl, WebUrl], _lnurl_decode(bech32))
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/pydantic/tools.py", line 35, in parse_obj_as
Apr 25 09:59:50 host sh[32242]:     return model_type(__root__=obj).__root__
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/pydantic/main.py", line 338, in __init__
Apr 25 09:59:50 host sh[32242]:     raise validation_error
Apr 25 09:59:50 host sh[32242]: pydantic.error_wrappers.ValidationError: 2 validation errors for ParsingModel[Union[lnurl.types.TorUrl, lnurl.types.WebUrl]]
Apr 25 09:59:50 host sh[32242]: __root__
Apr 25 09:59:50 host sh[32242]:   URL host invalid, top level domain required (type=value_error.url.host)
Apr 25 09:59:50 host sh[32242]: __root__
Apr 25 09:59:50 host sh[32242]:   URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'https'})
Apr 25 09:59:50 host sh[32242]: During handling of the above exception, another exception occurred:
Apr 25 09:59:50 host sh[32242]: Traceback (most recent call last):
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 25 09:59:50 host sh[32242]:     response = self.full_dispatch_request()
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 25 09:59:50 host sh[32242]:     rv = self.handle_user_exception(e)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 25 09:59:50 host sh[32242]:     reraise(exc_type, exc_value, tb)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Apr 25 09:59:50 host sh[32242]:     raise value
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 25 09:59:50 host sh[32242]:     rv = self.dispatch_request()
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 25 09:59:50 host sh[32242]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/lnbits/lnbits/decorators.py", line 23, in wrapped_view
Apr 25 09:59:50 host sh[32242]:     return view(**kwargs)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/lnbits/lnbits/decorators.py", line 43, in wrapped_view
Apr 25 09:59:50 host sh[32242]:     return view(**kwargs)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/lnbits/lnbits/extensions/withdraw/views_api.py", line 88, in api_link_create_or_update
Apr 25 09:59:50 host sh[32242]:     return jsonify({**link._asdict(), **{"lnurl": link.lnurl}}), Status.OK if link_id else Status.CREATED
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/lnbits/lnbits/extensions/withdraw/models.py", line 30, in lnurl
Apr 25 09:59:50 host sh[32242]:     return lnurl_encode(url)
Apr 25 09:59:50 host sh[32242]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-SsORkRR7/lib/python3.7/site-packages/lnurl/core.py", line 26, in encode
Apr 25 09:59:50 host sh[32242]:     raise InvalidUrl
Apr 25 09:59:50 host sh[32242]: lnurl.exceptions.InvalidUrl

**Comment by frennkie** [comment]
If this shouldn't work then at least the error message should be more helpful.

**Comment by arcbtc** [comment]
LNURL needs to be over https or TOR, we did have some way of making this clearer to self-hosted users, but not sure where it's gone. 
We had a ver LNBITS_FORCE_HTTPS=0
I'll work out a tooltip or something to make it clearer

**Comment by frennkie** [comment]
I have `LNBITS_FORCE_HTTPS=0` in my .env... doesn't work despite this.

**Comment by eillarra** [comment]
LNbits should also be used with HTTPS, that's the recommended way. This .env variable exists mainly to allow the use of LNbits with Tor. Using LNbits without HTTP on mainnet **is not recommended**.

In any case: if you are using HTTP on mainnet, LNURL will never work, because the spec doesn't support it. In this case, we should block the extension altogether. No wallet is going to work if you share via HTTP on mainnet.

**Comment by eillarra** [comment]
If you just want to test the withdraw extension on `localhost` you need to use `ngrok` or something similar to be able to test the withdraws with real wallets. This should be documented.

**Comment by arcbtc** [comment]
Added a warning to the about to make it a little clearer 
https://github.com/arcbtc/lnbits/commit/1c8beba80bb809b25ffc64695777e1e8c8586341

**Comment by HamishMacEwan** [comment]
Just so you know how far out of my depth I am, myNode runs lnbits as http:// on port 5000, and I've used hitch (https://hitch-tls.org/) and a letsencrypt cert to make it appear as https:// at 50011 with sufficient CA credibility to access the camera on my handset/desktop. 

Whenever I visit 

`https://myClearnet.nz:50011/lnurlp/?usr=88f0695770cf4751a9e9ecc940e12b43`

![chrome_w7chvOgDQ2](https://user-images.githubusercontent.com/388061/94979508-955fc880-057f-11eb-891a-ad7852c5d0f2.png)

Is the warning.  I'm guessing that this is what lnbits sees from the hitch redirection, an http:// connection.

The log of attempting to create an LNURL-pay request is attached.

[lnurlp.error.txt](https://github.com/lnbits/lnbits/files/5320863/lnurlp.error.txt)

The complaint seems to be that the URL schema is http://, despite, as above, efforts to make it https://

**Comment by fiatjaf** [comment]
What LNbits version?
Did you try to set the environment variable `LNBITS_FORCE_HTTPS`?

**Comment by HamishMacEwan** [comment]
> What LNbits version?

Current master, up to commit https://github.com/lnbits/lnbits/commit/e2f6c20e3bd64dcff4c7c28d6f081256c372a520 

> Did you try to set the environment variable `LNBITS_FORCE_HTTPS`?

It was set in .env.sample and I didn't change it.

I have run lnbits using this command:

```
./venv/bin/hypercorn --certfile mynode.local.hitch.pem --keyfile mynode.local.hitch.pem --bind 0.0.0.0:50010 'lnbits.app:
create_app()'
```

And not only does it work, it has presented all the LNURL-pay links I had been trying to create:

![chrome_DNEFTcuplb](https://user-images.githubusercontent.com/388061/94980434-381b4580-0586-11eb-97cd-f6487199b023.png)
